apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-ts
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      api: app-ts
  template:
    metadata:
      labels:
        api: app-ts
    spec:
      containers:
      - name: app-ts
        image: paulolemosdev/app-ts:v2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000
